### ISSUE TITLE
wg on usg: routing all traffic to vpn peer

### ISSUE THREAD

**Issue by lazersandstuff** [Lochnair/vyatta-wireguard#10]
Hi,

thanks to all who were involved in building wireguard (jason) and of course you guys building it for edgeOS devices! 

It seems like the cryptorouting and the routing table of the OS are getting in the way of each other (or I am just not getting it how to configure it properly) :) 

I set the configuration options as described and the tunnel is up (I can ping the rfc1918 ip of my peer which is directly connected to the internet). so far so good, but how can i route my LAN traffic heading to the internet via the wg0 interface? I want to tunnel all traffic so I configured the allowed-ips to be 0.0.0.0/0, because as I understand it the allowed-ips are used for access control and for routing decisions. I also set the route-allowed-ips option. But when I look in my routing table with "ip route" the default route still points to my router connecting the USG with the internet (which probably is ok because otherwise the tunnel would go down). But how should this work? As I said I can ping the private IP of my peer...but when I check my public ip, it is still the one from my provider and not the one from my vpn peer.

Any ideas? Should this work or is wireguard not build to act as a vpn gateway, but just as a vpn client? Or is this something which is not supported yet on edgeOS? Are you guys doing the same and it works? 

Thanks for the help!

**Comment by Lochnair** [comment]
If you set `route-allowed-ips: true` a default route on the wg interface will be added to your routing table. However if there's already a default route there the commit will fail, since it can't replace the route.

As you note you can't just remove the default route to your modem and add the WireGuard default route and expect it to work. You can get around this by doing `set interfaces wireguard wgX fwmark 0x50`. This marks outgoing encrypted packets with the mark 0x50. We'll use this with PBR to send encrypted packets via your modem.

Following that train of thought, we need to add an extra routing table for encrypted traffic:
`eth1` is your WAN interface
`192.168.0.1` is your ISP gateway
Adjust as necessary.
```
set protocols static table 50 interface-route 192.168.0.0/24 next-hop-interface eth1
set protocols static table 50 route 0.0.0.0/0 next-hop 192.168.0.1
```

Now we have a routing table for WireGuard to send encrypted packets to. Lastly we need to make sure packets marked with 0x50 are sent to routing table 50. Unfortunately Vyatta/EdgeOS doesn't support policy-based routing on packets originating on the `lo` interface, so we'll have to use `ip rule` directly with [post-config.d](https://community.ubnt.com/t5/tkb/articleprintpage/tkb-id/EdgeMAX_FAQ/article-id/3).
```
ip rule add pref 50 fwmark 0x50 iif lo lookup 50
```

If you're using DHCP on your WAN interface you should disabling adding the provided default route:
```
set interfaces ethernet eth1 dhcp-options default-route no-update
```

**Comment by lazersandstuff** [comment]
So not only is this not really a bug of the package you even explained to me something which should be basics for a ubiquiti owner :) Thank you so much! I will go ahead and try this on the weekend!

**Comment by Lochnair** [comment]
Hey I'm happy to help :)

**Comment by lazersandstuff** [comment]
Thx for the help again, but unfortunately it seems that I am doing this wrong...could you check my config for mistakes? 

eth0 is my outside interface with the ip address 192.168.8.100/24. the default gateway there (my modem) has 192.168.8.1/24. i have a tunnel established because i can ping the private ip of my wg peer, but when i check my public ip it is still the one from my provider. i tried your config, but had to modify it slightly because it looks like USG wants the fwmark in decimal and not in hex.

set interfaces wireguard wg0 address 192.168.41.1/24
set interfaces wireguard wg0 listen-port 51820

set interfaces wireguard wg0 peer somebase64encodedpublickey= endpoint 1.2.3.4:51820
set interfaces wireguard wg0 peer somebase64encodedpublickey= allowed-ips 0.0.0.0/0

set interfaces wireguard wg0 private-key /config/auth/wg.key

set interfaces wireguard wg0 fwmark 50
set protocols static table 50 interface-route 192.168.8.0/24 next-hop-interface eth0
set protocols static table 50 route 0.0.0.0/0 next-hop 192.168.8.1

cat /config/scripts/post-config.d/10-wireguard 
ip rule add pref 50 fwmark 50 iif lo lookup 50

I thought maybe usg config wants the fwmark in decimal and ip rule wants it in hex so I even tried the post-config.d command with 0x32 (decimal 50). Funny thing is that on the cli both versions are accepted so I cant figure out which is the correct syntax for this plattform...either way, doesn't work :/

any clues where i messed up? the script in post-config.d just has to be chmodded +x, right?

**Comment by Lochnair** [comment]
Did you disable the default route from the ISP modem and add a static one for your WireGuard gateway?
If you can ping through the WG tunnel, then that's most likely what's wrong.

**Comment by Lochnair** [comment]
@lazersandstuff Did you ever get this working?

**Comment by Lochnair** [comment]
Right, since I haven't heard back in over a month, I'm closing this issue.
I'll reopen it if you still need help.

**Comment by asapkota** [comment]
@Lochnair question regarding your post above. How does this work if your WAN interface has a dynamic ip from the ISP that changes everyday (along with the gateway)?

**Comment by asapkota** [comment]
I am trying to get wg setup as a full tunnel and route all traffic from client devices (mobile phones, laptops etc). I can connect the client to the USG. I can access local resources but cannot connect to anything on the Internet when the tunnel is active. Thanks

**Comment by Lochnair** [comment]
@asapkota 
It doesn't. You could probably do something like this:

Create a static routing table containing a default route to your VPN gateway. You can also create a blackhole rule to make sure traffic never goes over the unencrypted WAN link if the VPN connection drops.

```bash
set protocols static table 50 route 0.0.0.0/0 next-hop <VPN_GW>
set protocols static table 50 route 0.0.0.0 blackhole distance 255
```

**Note:** The newest rule is processed first if you don't specify preference
First we'll add a rule that directs any traffic without WireGuards fwmark to the routing table we created earlier. Then we'll add a rule for the main routing table that only catches traffic that's not /0. This makes sure routes for local traffic still works.

```bash
ip rule add not fwmark 50 lookup 50
ip rule add lookup main suppress_prefixlength 0
```

**Comment by asapkota** [comment]
So compiling everything from above, is this correct?

set interfaces wireguard wg0 address 10.0.105.1/24 (vpn server)
set interfaces wireguard wg0 listen-port someport
set interfaces wireguard wg0 route-allowed-ips false
set interfaces wireguard wg0 peer somepubickey allowed-ips 10.0.105.101/32 (client1)
set interfaces wireguard wg0 peer somepubickey allowed-ips 10.0.105.102/32 (client2)
set interfaces wireguard wg0 private-key /config/auth/privatekey
set interfaces wireguard wg0 fwmark 0x50

set protocols static table 50 route 0.0.0.0/0 next-hop 10.0.105.1 (VPN gateway?)
set protocols static table 50 route 0.0.0.0 blackhole distance 255

ip rule add not fwmark 50 lookup 50
ip rule add lookup main suppress_prefixlength 0
