### ISSUE TITLE
Wireguard interface absent after upgrading from v1 to v2 firmware

### ISSUE THREAD

**Issue by deimosfr** [Lochnair/vyatta-wireguard#106]
Hi,

I was using Wireguard with 1.9 version without any issues. I upgraded EdgeRouter to v2 and installed Wireguard in v2 but the interface does not show up. The configuration is still present, but even after rebooting, I don't see any interface.

wg command doesn't show anything as well. Any idea ?

Thanks

**Comment by JacobHenner** [comment]
Experiencing the same problem using EdgeOS 2.0.1 on an EdgeRouter Lite. Looks like the module exists for kernel 3.10.107-UBNT, but not 4.9.79-UBNT.

**Comment by JacobHenner** [comment]
@deimosfr Check https://github.com/Lochnair/vyatta-wireguard/releases for the latest v2 release - I made the same mistake.
