### ISSUE TITLE
snapshot 0.0.20190601 has wrong kernel version.

### ISSUE THREAD

**Issue by pervrosen** [Lochnair/vyatta-wireguard#110]
Should have "4.14.54-UBNT", with EdgeOS v2.04 (latest) on EdgeRouter X, accoding to modprobe but had 3..something instead. Think it was 3.10.107-UBNT but cannot confirm. Hope it helps. BR, PvR

**Comment by feuerrot** [comment]
The current kernel version on the EdgeRouter Lite (e100) running version `v2.0.4.5199165.190605.1549` is `4.9.79-UBNT`, while the latest snapshot installs a kernel module for `3.10.107-UBNT`.

**Comment by Lochnair** [comment]
Packages for v2.0.x are under the same release as the rest as requested in #93, to make things easier for people with update scripts.
