### ISSUE TITLE
Create Docker build scripts

### ISSUE THREAD

**Issue by rickard-von-essen** [Lochnair/vyatta-wireguard#112]
I was looking into rebuild these packages and started to create some scripts that could be used together with Docker to spit out packages based on the documentation in [build from scratch](https://github.com/Lochnair/vyatta-wireguard#build-from-scratch). But then I saw that you already use such setup in [Jenkins build](https://build.lochnair.net/job/ubiquiti/job/wireguard-fw2.0/lastCompletedBuild/console). Maybe you can publish the source for the docker build images.

**Comment by Lochnair** [comment]
All the Dockerfiles I use are available here (one branch per image): https://github.com/Lochnair/dockerfiles

Each image is built by automatically by Jenkins and then pushed to Docker Hub.
