### ISSUE TITLE
0.0.20190702 wrong kernel version for Edge X (50)

### ISSUE THREAD

**Issue by doc1623** [Lochnair/vyatta-wireguard#113]
I'm trying to install this for the first time but, unless I'm mistaken this won't work. 

user@ubnt:~$ uname -a
Linux ubnt 4.14.54-UBNT #1 SMP Wed Jun 5 15:55:46 UTC 2019 mips GNU/Linux
user@ubnt:~$ ls /root.dev/w/lib/modules/
3.10.107-UBNT  4.14.54-UBNT

/root.dev/w/lib/modules/3.10.107-UBNT/kernel/net/wireguard.ko

user@ubnt:~$ dpkg -l|grep wireguard
ii  wireguard                           0.0.20190702-1                                           mipsel       fast, modern, secure kernel VPN tunnel

larry@ubnt:~$ show version
Version:      v2.0.4
Build ID:     5199165
Build on:     06/05/19 15:49
Copyright:    2012-2018 Ubiquiti Networks, Inc.
HW model:     EdgeRouter X 5-Port
Uptime:       15:36:04 up 50 min,  2 users,  load average: 1.00, 1.04, 1.02

**Comment by doc1623** [comment]
I should have not upgraded the firmware first thing. I specifically bought this router to work with mullvad vpn but I did. It seems to be running 4.14.54-UBNT

**Comment by mbilker** [comment]
There's two versions of the wireguard deb package. The ones with v2.0 are for the v2.0 firmware, which is the one you installed.

**Comment by mbilker** [comment]
Also, this issue is a dupe of #111

**Comment by doc1623** [comment]
I did see that issue but the initiator said he downloaded the wrong version

I believe, I downloaded and installed the correct version but it's not built for the version kernel on the router. In the other issue people are talking about kernel 4.9. My router has kernel 4.14.54 but the deb built it for 3.10.107 (see the kernel module directory above)

If I'm incorrect, please let me know what I'm misunderstanding

**Comment by mbilker** [comment]
I upgraded my ER-X to 2.0.4 and I now have kernel version:
```
Linux ubnt 4.14.54-UBNT #1 SMP Wed Jun 5 15:55:46 UTC 2019 mips GNU/Linux
```
So you installed the deb for the wrong firmware version.

**Comment by mbilker** [comment]
@doc1623 I recommend you close this issue.

**Comment by begetan** [comment]
>My router has kernel 4.14.54 but the deb built it for 3.10.107 (see the kernel module directory above)

Because you've download version for the Edge Router 1.10.x not 2.0.x
There are two builds for 1.10.x and 2.0.x version for each release

**Comment by doc1623** [comment]
My mistake. Closing
