### ISSUE TITLE
Wireguard kernel

### ISSUE THREAD

**Issue by droidforever** [Lochnair/vyatta-wireguard#119]
Can someone share their 3.1.107 kernel.  I am really lost and have no idea how to compile a kernel?  i installed the latest .deb file "E50" in my ER-X router but the module for the kernel does not appear to be loaded.  My ER-X is v2.6

**Comment by dawidroz** [comment]
Did u install version for 2.x firmware? On my machine with 2.0.6 all works fine

**Comment by droidforever** [comment]
Maybe I am trying to set the interface incorrectly.  I have found several guides but they all seem to use different commands under configure.  I tried using Vyatta's example but I get an error about routing.  I am trying to route a Torguard Wireguard VPN through my EdgeRouterX so that anything connecting to the router goes through the wireguard interface.  Maybe this is not possible?  Any chance you could point me to a guide that follows my intent of usage?

**Comment by Lochnair** [comment]
You've probably installed the version for the v1.10 FW as @dawidroz points out. This is the package you should use: [wireguard-v2.0-e50-0.0.20190913-1.deb](https://github.com/Lochnair/vyatta-wireguard/releases/download/0.0.20190913-1/wireguard-v2.0-e50-0.0.20190913-1.deb) - which contains the module for the 4.14.54 kernel.

**Comment by droidforever** [comment]
Okay that worked thank you very much.  But now I am getting another error:
Error: Allowed IP default on interface wg0 peer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx conflicts with an existing route. route-allowed-ips cannot be enabled.
Your assistance is valued and appreciated.

**Comment by Lochnair** [comment]
I'm guessing you have 0.0.0.0/0 in your allowed-ips, **and** have a default gateway from your ISP in your routing table. In which case the route-allowed-ips option won't be able to route traffic through the wg interface automatically.

There are multiple approaches to resolving this, but I'll need to know your use case to know what'll work best for you.

**Comment by droidforever** [comment]
okay I'll do my best to describe my setup.  I am connected through Spectrum to my router.  Here are the steps I took
root@ubnt:/home/admin# configure
[edit]
root@ubnt# set interfaces wireguard wg0 address 10.29.1.25/24
[edit]
root@ubnt# set interfaces wireguard wg0 listen-port 51820
[edit]
root@ubnt# set interfaces wireguard wg0 route-allowed-ips true
[edit]
root@ubnt# set interfaces wireguard wg0 peer publickey from Torguard endpoint 159.65.251.112:443
[edit]
root@ubnt# set interfaces wireguard wg0 peer publickey from Torguard allowed-ips 0.0.0.0/0
[edit]
root@ubnt# set interfaces wireguard wg0 private-key My privatekey from Torguard
[edit]
root@ubnt# set firewall name WAN_LOCAL rule 20 action accept
[edit]
root@ubnt# set firewall name WAN_LOCAL rule 20 protocol udp
[edit]
root@ubnt# set firewall name WAN_LOCAL rule 20 description 'WireGuard'
[edit]
root@ubnt# set firewall name WAN_LOCAL rule 20 destination port 51820
[edit]
root@ubnt# 
[edit]
root@ubnt# commit
[ interfaces wireguard wg0 ]
Error: Allowed IP default on interface wg0 peer ZBvdkjaT6t2h3k/MQjLDgqM/F1JfOB5Vgm3mLkySUhY= conflicts with an existing route. route-allowed-ips cannot be enabled.

**Comment by droidforever** [comment]
I changed this line:
set interfaces wireguard wg0 peer publickey from Torguard allowed-ips 0.0.0.0/0
to:
set interfaces wireguard wg0 peer publickey from Torguard allowed-ips ip provided by torgard 
This brought up an interface but my next question is how to set a routing table for the wireguard connection to my internal network?

**Comment by Lochnair** [comment]
Yeah that won't work. You might wanna get a better understanding of the cryptokey routing in WireGuard.

This guide describes more or less what you want to do:
https://andrew.dunn.dev/posts/wireguard-from-your-isp/

**Comment by storrgie** [comment]
@droidforever I'm happy to answer questions about the article, but I think you've gotta front to back a deployment to understand the fundamentals. That thing I wrote is pretty well a good way to dip your toes in because you're not worrying about both sides of the tunnel (as a provider has handled the configuration on the other side).

**Comment by droidforever** [comment]
Thank you I will check it out tonight!  I really appreciate the community's assistance!!!

**Comment by droidforever** [comment]
okay I read the article but I'm in the very early stages of memory loss and short term memory is a problem for me so I couldn't absorb much.  I did follow the setup guide and got the interface  up but I am not sure where to go from there.  How do I add my internal networked devices to MullvadHome?  I am totally lost at this point.  I truly appreciate everyone's help.

**Comment by droidforever** [comment]
Is there another process I need to go through before the guide I followed?  Do I need to follow this guide https://andrew.dunn.dev/posts/home-network-a-novice-design/ first?  My equipment is as follows.  Spectrum pass thorugh modem.  An Edgerouter X.  A TP--Link managed switch.  Is this possible with this equipment.  I am really frustrated trying to get this to work.  Any help at all is appreciated.

**Comment by droidforever** [comment]
could not get this to work.  Thank you for your replies.

**Comment by valentt** [comment]
I have correct version of wireguard package for 2.x ER-X firmware but I also have this issue.
Has the author tried using 2.x firmware and setting up wireguard after running basic wizard? @droidforever is there anything else I should do or not do?

**Comment by valentt** [comment]
I switched to 1.10.10 firmware and if wizard is run and eth0 is configured as wan port with nat and default gateway then I still get the same error and can't run "set interfaces wireguard wg0 route-allowed-ips true" only "set interfaces wireguard wg0 route-allowed-ips false" works because default router is already configured or I get this message:

Error: Allowed IP default on interface wg0 peer conflicts with an existing route. route-allowed-ips cannot be enabled.

**Comment by droidforever** [comment]
I closed this because I was unable to get this working.  I wish you luck and am sorry I am unable to assist you.
