### ISSUE TITLE
Suggestion for config of peers.

### ISSUE THREAD

**Issue by mjbnz** [Lochnair/vyatta-wireguard#127]
It feels cumbersome to have peers defined by their public keys, so I wonder if the vyos method of peer configuration might be cleaner? (Also, tab completion seems to not work after a peer's public key, I wonder if that's related?)

So, instead of:
```
set interfaces wireguard wg0 peer nyYWxu84tU+AdYdEoHf3ej6dcfF1ClhP4cB0vCRjE3g= endpoint '1.2.3.4:51820'
set interfaces wireguard wg0 peer nyYWxu84tU+AdYdEoHf3ej6dcfF1ClhP4cB0vCRjE3g= description PEER1
set interfaces wireguard wg0 peer nyYWxu84tU+AdYdEoHf3ej6dcfF1ClhP4cB0vCRjE3g= allowed-ips 0.0.0.0/0
```

Something like:
```
set interfaces wireguard wg0 peer PEER1 endpoint '1.2.3.4:51820'
set interfaces wireguard wg0 peer PEER1 public-key nyYWxu84tU+AdYdEoHf3ej6dcfF1ClhP4cB0vCRjE3g=
set interfaces wireguard wg0 peer PEER1 allowed-ips 0.0.0.0/0
```

**Comment by 111A5AB1** [comment]
This seems to be a duplicate of #92 ?

**Comment by mjbnz** [comment]
Guilty. I didn't search hard enough. Yes, @Lochnair 's breaking change proposal is what I'd prefer.

Closing this issue.
