### ISSUE TITLE
Support EdgeMax 2.0.x releases

### ISSUE THREAD

**Issue by gnoack** [Lochnair/vyatta-wireguard#131]
Thanks for the excellent Wireguard integration!

I ran into a problem with an EdgeRouter X SFP when I upgraded the EdgeRouter firmware to the 2.0.x version:

**With version 1.10.10, things work as expected**:
 - Install 1.10.10 firmware from https://www.ui.com/download/edgemax/edgerouter-x-sfp
 - Copy over the `wireguard-e50-0.0.20191012-1.deb` package and install it.

**Attempting the same thing with the 2.0.8 version**:
 - Install 2.0.8 firmware from https://www.ui.com/download/edgemax/edgerouter-x-sfp
 - Copy over the `wireguard-e50-0.0.20191012-1.deb` package and try to install it.

**Expected result**: `wireguard` package can be installed
**Observed result**: Package can't be installed because the kernel versions are not matching.

Is there a chance you could provide packages for the 2.0.x firmware releases?

Thanks,
Günther

**Comment by Lochnair** [comment]
It already does.

You need the package with v2 in it: https://github.com/Lochnair/vyatta-wireguard/releases/download/0.0.20191012-1/wireguard-v2.0-e50-0.0.20191012-1.deb

**Comment by gnoack** [comment]
Thanks, Nils! I overlooked that in the package list!
