### ISSUE TITLE
20191012 Setting an IPv6 address on wg0 not possible

### ISSUE THREAD

**Issue by derneue** [Lochnair/vyatta-wireguard#133]
I tried to setup ipv6 on the wg0 interface but I receive this error:

`
ubnt@ubnt# set interfaces wireguard wg0 address 10.8.0.1/24,fc00:17:8::1/64
"10.8.0.1/24,fc00:17:8::1/64" is not a valid value
Value validation failed
Set failed
[edit]
`
Why is the value not valid?
Any ideas?

**Comment by SlothCroissant** [comment]
Do two different set commands, one for each address.

**Comment by derneue** [comment]
That did the trick. Thank you.
