### ISSUE TITLE
Error installing 20191219 via dpkg - firmware version 1.x

### ISSUE THREAD

**Issue by bohannin** [Lochnair/vyatta-wireguard#134]
Preparing to replace wireguard 0.0.20191012-1 (using wireguard-e100-0.0.20191219-1.deb) ...
Unpacking replacement wireguard ...
dpkg: error processing wireguard-e100-0.0.20191219-1.deb (--install):
 trying to overwrite '/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp6/interface-type/node.def', which is also in package vyatta-cfg-firewall 1:0.14.13+t5166931-dev-v1.10.9-f87a386
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 wireguard-e100-0.0.20191219-1.deb

**Comment by nextstepp** [comment]
I get exactly the same error message on Firmware V2.0.8 Edgerouter POE 5 using V2 deb package.

**Comment by Lochnair** [comment]
Yep, didn't realize the version for the mss-clamp6 divert wasn't bumped.

Fix coming.

**Comment by nextstepp** [comment]
Thanks for quick reply , after the fix i will test it heavily and share my feedback.

**Comment by Lochnair** [comment]
Updated the release with new packages that should be okay.

@nextstepp Can you confirm?

**Comment by nextstepp** [comment]
@Lochnair I confirm that I installed successfully after the fix , edgerouter is receiving traffic from peers , seems issue resolved.

**Comment by Lochnair** [comment]
Sweet, thank you. Closing this then.

**Comment by nextstepp** [comment]
Thank you @Lochnair .
