### ISSUE TITLE
Recommended upgrading procedure

### ISSUE THREAD

**Issue by lorenz** [Lochnair/vyatta-wireguard#14]
What is currently the best way to upgrade an EdgeRouter with WireGuard installed? I've previously removed all WireGuard settings, installed the upgrade, reinstalled WireGuard and readded the settings back, but that is pretty tedious for every update.

**Comment by Lochnair** [comment]
Oh, there's no need for that.

The only time I'd advice removing the configuration first, is if we'd done some big changes to the Vyatta configuration syntax. And if that ever happens I'll make sure to add it to the release announcement.

**Comment by lorenz** [comment]
So the best way is upgrade firmware, reboot, reinstall WireGuard, reboot?

**Comment by Lochnair** [comment]
I read your question a bit too fast, I though you were asking about upgrading WireGuard.

I tested removing the wireguard package and rebooting just now. When it comes back up the WireGuard configuration will seemingly be gone, but if you reinstall the package and then reboot it comes back.

So most likely you can just upgrade and then reinstall WireGuard afterwards, and the configuration will be back.

Just a warning, when the package is removed the vyatta-cfg system notices and tries to remove all related configuration entries. They are however not saved to /config/config.boot, so as long as you do *not* save the config afterwards, it should be fine.

**Comment by neilalexander** [comment]
If you perform a system upgrade then the package will effectively be "uninstalled" and when the system boots up with those wireguard templates missing, the wireguard configuration will be stripped from the running config. Importantly, though, it will not be removed from the saved config.

Therefore you can just reinstall the wireguard package, open `configure`, type `load` to reload from your saved config, `commit` to make effective and you should be back.
