### ISSUE TITLE
Endpoint IP address does not update with dynamic IP hosts (served by a dyndns service)

### ISSUE THREAD

**Issue by dlbogdan** [Lochnair/vyatta-wireguard#15]
So the issue here as best as I can describe it :
Both endopoints are on dynamic IPV4 addresses and have in place ddns  for both. 
The tunnel stops working as soon as one endpoint changes address in which case the defined configuration showed by sudo wg showconf wg0 is not in sync anymore with the actual ip address that the DDNS already updated for the host.
 
example:
 
ER1:$ sudo wg showconf wg0
[Interface]
ListenPort = 51820
PrivateKey = 
[Peer]
PublicKey = 
AllowedIPs = 10.0.0.0/8
Endpoint = 93.115.66.178:51820
 
ER1:$ ping endpoint2.ddns.url 
PING  endpoint2.ddns (188.213.155.30) 56(84) bytes of data.
 (the addresses and hostnames are fiction)

the endpoints are configured with the proper ddns names but the IPs never gets updated on the run. Till now to get the VPN going again I have to reboot the router (the one with the mismatched IPs from the wg standpoind vs the real one)
 
Is there a solution to this ? 
Also is there a way to reset the connection ? Already tried sudo ifconfig wg0 down and then up and it doesn't reset the connection.

**Comment by dlbogdan** [comment]
I'd say this is fixed when you set endpoints to both ends and persistent-keepalive values. 
It however does not work with roadwarrior configs.

**Comment by Lochnair** [comment]
Issues like this isn't really vyatta-wireguard specific, so I'd advise asking on the [WireGuard mailing list](https://lists.zx2c4.com/mailman/listinfo/wireguard) instead.

**Comment by DanielDent** [comment]
According to https://community.ubnt.com/t5/EdgeMAX/Release-WireGuard-for-EdgeRouter/m-p/2102980/highlight/true#M181852 the recommended solution for some situations is to periodically run the wg utility so that it can re-resolve the DNS entry and update the kernel with the new IP address if required.

At the moment "just add a cronjob/busy loop" appears to be the recommended approach.

Syntax such as the following would be great:

```
interfaces {
    wireguard wg0 {
        private-key "iO3YxEZM5KNmdST1XYtv1xQ8AM3y12+/K+QFKY7rflw="
        address "192.168.33.1/24"
        listen-port 51820

        peer "aBaxDzgsyDk58eax6lt3CLedDt6SlVHnDxLG2K5UdV4=" {
            allowed-ips "192.168.33.101/32"
            endpoint "example1.example.net:51820"
        }
        peer "GIPWDet2eswjz1JphYFb51sh6I+CwvzOoVyD7z7kZVc=" {
            allowed-ips "192.168.33.102/32,192.168.33.103/32"
            endpoint "anotherexample.example.org:29922"
            reresolve-interval 5m
        }
    }
}
```

e.g. with 'reresolve-interval 5m' added to a peer, the wg command would be re-run every 5 minutes.
