### ISSUE TITLE
GRE-Bridge over wireguard tunnel crashes the router(s)

### ISSUE THREAD

**Issue by dlbogdan** [Lochnair/vyatta-wireguard#16]
So let's say I want to get GRE-Bridge working on this tunnel because I need Layer2
The problem is that whenever there's high traffic involved one or both endpoint routers reboot (kernel panic?).
iperf3 for example ALWAYS makes one router reboot immediately.

**Comment by Lochnair** [comment]
As Jason mentioned on the UBNT forum, We'll need the kernel logs to debug this.
