### ISSUE TITLE
Setting non-file-based pre-shared key causes error on commit

### ISSUE THREAD

**Issue by ginkel** [Lochnair/vyatta-wireguard#33]
Using `wireguard-octeon-0.0.20171221-2.deb` on an EdgeRouter Lite:

```
user@erl# set interfaces wireguard wg0 peer $PEER preshared-key RFJsHB6YjbR9lkCNZSefOD+QVERVbRnVLrFTGG8M7Ds=
[edit]
user@erl# commit
[ interfaces wireguard wg0 peer $PEER preshared-key RFJsHB6YjbR9lkCNZSefOD+QVERVbRnVLrFTGG8M7Ds= ]
sh: -c: line 0: syntax error near unexpected token `fi'
sh: -c: line 0: `if [[ !("RFJsHB6YjbR9lkCNZSefOD+QVERVbRnVLrFTGG8M7Ds=" =~ ^[0-9a-zA-Z/+]{43}=$) ]]; [[ -e RFJsHB6YjbR9lkCNZSefOD+QVERVbRnVLrFTGG8M7Ds= ]] || exit 1; fi'

Error: Preshared-key RFJsHB6YjbR9lkCNZSefOD+QVERVbRnVLrFTGG8M7Ds= not found

Commit failed
```

Seems as if the RegExp in https://github.com/Lochnair/vyatta-wireguard/blob/master/generic/opt/vyatta/share/vyatta-cfg/templates/interfaces/wireguard/node.tag/peer/node.tag/preshared-key/node.def matches 43 char keys instead of the 44 char keys generated by `wg genpsk`.

**Comment by ginkel** [comment]
Hm... Probably a duplicate of https://github.com/Lochnair/vyatta-wireguard/pull/32...

**Comment by ginkel** [comment]
Yep, working with 0.0.20171221-3. Sorry for the confusion.

**Comment by Lochnair** [comment]
Great, I was just about to ask you to try updating 👍
