### ISSUE TITLE
breakage on 1.10.0-beta.3

### ISSUE THREAD

**Issue by phixion** [Lochnair/vyatta-wireguard#36]
I'm on ERX 1.10.0-beta.3

phixion@lambda# commit
[ interfaces wireguard wg0 ]
RTNETLINK answers: Operation not supported

Commit failed

**Comment by Lochnair** [comment]
That's to be expected as we don't have the GPL sources for 1.10 yet. Nothing we can do about this until Ubiquiti releases 1.10 sometime next week.

**Comment by maxried** [comment]
Hi there! When do you expect a 1.10 compatible build?

**Comment by Lochnair** [comment]
Hard to say. Ubiquiti said that the GPL archives are will come next week, so likely a day or two after they release.
