### ISSUE TITLE
"Inappropriate ioctl for device" when committing config

### ISSUE THREAD

**Issue by dmayer** [Lochnair/vyatta-wireguard#37]
Hi,

I'm running version `vyatta-wireguard-0.0.20180118-1` on an EdgeRouter Lite (kernel 3.10.20-UBNT). 

I've been able to manually set up a wireguard tunnel using `wg` and `ip` commands. However, when I try to use the router config, I am getting the following error when executing `commit`:

```
[ interfaces wireguard wg0 peer Y7LI8pXkKrlMHuMk1RT4JFXx7+kX9Xb1GkvH0mPwHw4= ]
fread: Inappropriate ioctl for device
```

This is the config I'm trying to apply (I have tried variations including `endpoint` etc.)

```
+wireguard wg0 {
+    address 192.168.10.254/24
+    listen-port 51820
+    peer Y7LI8pXkKrlMHuMk1RT4JFXx7+kX9Xb1GkvH0mPwHw4= {
+        allowed-ips 0.0.0.0/0
+    }
+    private-key /config/auth/privatekey
+}
```

**Comment by Lochnair** [comment]
Just fixed this in 0.0.20180118-2.
