### ISSUE TITLE
Release Process

### ISSUE THREAD

**Issue by zx2c4** [Lochnair/vyatta-wireguard#4]
This repo should very closely track upstream snapshots. The release process should involve *replacing* the existing release with a new one, while still keeping older tags. The `Version: ` tag in https://github.com/Lochnair/vyatta-wireguard/blob/master/debian/control should be updated, committed, and then that commit tagged. Then,

![image](https://cloud.githubusercontent.com/assets/10643/25339945/8168253a-2904-11e7-879e-46d16df9b98e.png)

**Comment by neilalexander** [comment]
@Lochnair We could look to leverage a CI service for building each release?

**Comment by Lochnair** [comment]
@neilalexander Sorry for the late reply. My original plan was to use Jenkins to run automatic builds whenever a new snapshot is released. I didn't expect the `vyatta-wireguard` package and the binaries to get this tightly coupled though.

IMO the WireGuard binaries should be a separate package and **not** bundled with the Vyatta module. Decoupling them allows me to more easily provide automated builds tracking the latest WireGuard snapshot. The `vyatta-wireguard` package could have its own versioning and a dependency on the `wireguard` package.

**Comment by lox** [comment]
Been closely following wireguard and this project, let me know if we can provide a free account on buildkite.com for CI.

**Comment by zx2c4** [comment]
Hi @lox - We've actually got some nice infra of our own over on build.wireguard.com which we use for automated builds. If you think that buildkite could offer better performance than what we're currently getting, I'd be very interested. Shoot an email to team@wireguard.com and I can send over what we're currently running on our build server, if you want to see if buildkite is up to the task.
