### ISSUE TITLE
WG for Edgerouter 2.0

### ISSUE THREAD

**Issue by hwchaos** [Lochnair/vyatta-wireguard#58]
Hi there,

any chance you can compile WG for the Edgerouter 2.0.0 (alpha1)?
https://community.ubnt.com/t5/EdgeMAX-Beta-Blog/New-EdgeRouter-firmware-2-0-0-alpha-1-has-been-released/ba-p/2376224

Eager to test the alpha, but wg is a must have on my router.

Thanks for all your effort :-)

Regards

**Comment by storrgie** [comment]
This project is dependent on Ubiquiti releasing the GPL archives, so unless those are out they cannot make a build. You should close the ticket.

**Comment by hwchaos** [comment]
Mea Culpa,

did not know. Thought might have worked with the cavium sdk, if available.

Regards

**Comment by Lochnair** [comment]
Sadly no. The kernel available in the public Cavium SDK is 4.9.57, while UBNT uses 4.9.79.
Please do nag them about kernel sources though. With such a big release I'd prefer to be able to test WireGuard on it before it enters GA.

**Comment by Lochnair** [comment]
UBNT-afomins promised us GPL sources for 2.0.0-alpha.2 whenever it comes out. So I'm reopening this to remind me to build new binaries when that happens.

**Comment by hwchaos** [comment]
@Lochnair 
alpha3 just got released. Maybe you should remind then guys at UBNT about their promise

**Comment by storrgie** [comment]
Kinda meta to remind a voluntary developer that he should go remind people who are paid (and have a legal obligation) to release this material. Dust off your forum account and remind them yourself @hwchaos.

**Comment by hwchaos** [comment]
As Lochnair stated above he had contact to someone at UBNT. I did not know if that promise was made via PM or in the forum. 
While you might seem to see that as a request or order, i just tried to communicate to lochnair, as he might not have been aware of the alpha3 release.

He has no obligation to me and I do know it is his voluntary work and efforts he puts in there.

**Comment by Lochnair** [comment]
@hwchaos 
FYI UBNT-afomins stated they'd release GPL sources with alpha2 here: https://community.ubnt.com/t5/EdgeRouter/Qualcomm-Fast-Path-SFE-for-the-EdgeRouters/m-p/2391854/highlight/true#M212279

In addition me and a couple others have asked about it on the forums without getting any response.

**Comment by Ordspilleren** [comment]
GPL sources for beta 2 are available: https://community.ubnt.com/t5/EdgeRouter-Beta/EdgeMAX-EdgeRouter-firmware-version-v2-0-0-beta-2-has-been/m-p/2595734/highlight/true#M24309

**Comment by Lochnair** [comment]
First snapshot for FW v2.0 is now out: https://github.com/Lochnair/vyatta-wireguard/releases/tag/v2.0-0.0.20181218-1
