### ISSUE TITLE
set firewall options mss-clamp interface-type wg

### ISSUE THREAD

**Issue by marcbou** [Lochnair/vyatta-wireguard#59]
It is useful to enable mss clamping only on wireguard interfaces with 
    "set firewall options mss-clamp interface-type wg"

the enclosed trivial patch to vyatta enables this.

--- /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.DIST
+++ /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def
@@ -1,11 +1,12 @@
 multi:
 type: txt
 help: Interface type(s)
-syntax:expression: $VAR(@) in "pppoe", "pptp", "tun", "vti", "all"; \
-    "Interface type must be \"pppoe\", \"pptp\", \"tun\", \"vti\", or \"all\""
+syntax:expression: $VAR(@) in "pppoe", "pptp", "tun", "vti", "wg", "all"; \
+    "Interface type must be \"pppoe\", \"pptp\", \"tun\", \"vti\", \"wg\", or \"all\""
 
 val_help: pppoe; PPPoE interfaces
 val_help: pptp; PPtP interfaces
 val_help: tun; Tunnel interfaces
 val_help: vti; Virtual Tunnel Interface
+val_help: wg; WireGuard Interfaces
 val_help: all; All interfaces

**Comment by vswee** [comment]
This works in the interim`sudo iptables -t mangle -I POSTROUTING 1 -p tcp -o wg+ --tcp-flags SYN SYN -j TCPMSS --set-mss 1200`

**Comment by rufoa** [comment]
This would be nice if possible. PR submitted
