### ISSUE TITLE
RTNETLINK answers: File exists

### ISSUE THREAD

**Issue by sskaje** [Lochnair/vyatta-wireguard#6]
ERX, 1.9.1.1

I tried execute config commands or edit config.boot then load commit, both error occurred.

conf like:
```
wireguard wg0 {
    address 192.168.10.50/24
    listen-port 54321
    peer xxxx= {
        allowed-ips 0.0.0.0/0
    }
    private-key /config/auth/xxx
}
```
load this, commit
```
root@ubnt# commit
[ interfaces wireguard wg0 ]
hi
RTNETLINK answers: File exists

Commit failed
```
I'm sure that wg0 is not configured, and to ensure it has gone, i deleted using ip link del, commit again and error again.

I checked /opt/vyatta/share/vyatta-cfg/templates/interfaces/wireguard/node.def, and made changes:
```
create: sudo ip addr show $VAR(@) >/dev/null 2>&1 || sudo ip link add dev $VAR(@) type wireguard
```
check before add

then error:
```
root@ubnt# commit
[ interfaces wireguard wg0 address 192.168.10.50/24 ]
RTNETLINK answers: File exists

Commit failed
[edit]
```
So /opt/vyatta/share/vyatta-cfg/templates/interfaces/wireguard/node.tag/address/node.def
```
create: sudo ip addr show $VAR(../@) >/dev/null 2>&1 || sudo ip addr add $VAR(@) dev $VAR(../@)
```

commit, 
```
root@ubnt# commit
[ interfaces wireguard wg0 ]
RTNETLINK answers: File exists

Commit failed
[edit]

```
again

/opt/vyatta/share/vyatta-cfg/templates/interfaces/wireguard/node.def
```
end: if [ "$COMMIT_ACTION" != DELETE ]; then
        sudo ip link set down dev $VAR(@)
        sudo ip link set up dev $VAR(@)
        for i in $(sudo wg show $VAR(@) allowed-ips | sed 's/^.*\t//;s/ /\n/g' | sort -nr -k 2 -t /); do
                [[ $(sudo ip route get "$i" 2>/dev/null) == *dev\ $VAR(@)\ * ]] || sudo ip addr show $VAR(@) >/dev/null 2>&1 || sudo ip route add "$i" dev $VAR(@)
        done
     fi
```
another check before ip route, and then commit passed.

I tried to change ip address, but since *address* is defined as **multi**, the 'change' became 'add', and there were two address entries under wg0.
commit, passed.

then I delete both, and add a third ip address:

```
root@ubnt# compare
No changes between working and active configurations
[edit]
root@ubnt# show interfaces wireguard 
 wireguard wg0 {
     address 192.168.10.50/24
     address 192.168.10.40/24
     listen-port 54321
     peer xxx= {
         allowed-ips 0.0.0.0/0
     }
     private-key /config/auth/wg.private
 }
[edit]

root@ubnt# delete interfaces wireguard wg0 address 192.168.10.50/24 
[edit]
root@ubnt# delete interfaces wireguard wg0 address 192.168.10.40/24 
[edit]
root@ubnt# set interfaces wireguard wg0 address 192.168.10.60/24 
[edit]
root@ubnt# commit
[ interfaces wireguard wg0 address 192.168.10.50/24 ]
RTNETLINK answers: Cannot assign requested address

Commit failed
[edit]
```

**Comment by markuslindenberg** [comment]
I hit this one when setting `allowed-ips` to the default route with an already existing default route. I didn't want to set the default route to the tunnel interface but have 0.0.0.0/0 as allowed-ips. 

Right now I can live without default route in the wg interface, but I can think of a lot of use cases where I would need to define `allowed-ips` independently of routes to the wg interface, like when using dynamic routing or policy routing.

**Comment by julianschuh** [comment]
Same here. I explicitly needed to whitelist all IPs in the tunnel, as the tunnel is used to carry arbitrary IP traffic.

I ended up editing the file /opt/vyatta/share/vyatta-cfg/templates/interfaces/wireguard/node.tag/address/node.def and removing the section
`        for i in $(sudo wg show $VAR(@) allowed-ips | sed 's/^.*\t//;s/ /\n/g' | sort -nr -k 2 -t /); do
                [[ $(sudo ip route get "$i" 2>/dev/null) == *dev\ $VAR(@)\ * ]] || sudo ip addr show $VAR(@) >/dev/null 2>&1 || sudo ip route add "$i" dev $VAR(@)
        done`

I don't really understand the goal here - if I would want to route traffic through the tunnel I would either give the interface an IP or add a static route - but from a semantics viewpoint I certainly would not expect the allowed-ips setting to create routes...

**Comment by sskaje** [comment]
@julianschuh I don't understand neither. **allowed-ip** is an entry for ACL, not for routing, so I just muted it to commit than fixing it.

**Comment by zx2c4** [comment]
@sskaje You are incorrect.

For incoming encrypted packets, allowed-ips is an ACL. However, for unencrypted outgoing packets, once a packet is routed to the WireGuard interface, allowed-ips determines which one of the WireGuard peers it should be encrypted for. So in this latter sense, it is also a routing table, within the interface.

----

It might be useful to have an option to disable adding routes based on allowed-ips. I doubt, though, that any of the things mentioned above would require that. For example, why are you trying to have two default routes in the first place?

**Comment by markuslindenberg** [comment]
* When doing dynamic routing using two wg interfaces I need to allow 0.0.0.0/0 on both interfaces and have the routes set by a routing daemon. That kind of setup means I need to have one wg interface per peer.
* When doing policy routing to multiple default routes I need to allow 0.0.0.0/0 on multiple interfaces and route according to the routing table assigned to the incoming flow.

I think that a wg interface's allowed-ips and the kernel's routing table(s) are different things that only match in the most simple static setups.

**Comment by zx2c4** [comment]
> When doing dynamic routing using two wg interfaces I need to allow 0.0.0.0/0 on both interfaces and have the routes set by a routing daemon. That kind of setup means I need to have one wg interface per peer.

Okay, we're on the same page then. This indeed is a good reason why you might not want all the allowed-ips turned into routes. I'll prepare a patch for this.

**Comment by zx2c4** [comment]
Alright, fixed.

https://github.com/Lochnair/vyatta-wireguard/releases

Download this latest release (I posted a `-2`), and then you'll be able to specify in your config file: `route-allowed-ips false` for the wireguard interface.

**Comment by markuslindenberg** [comment]
Just did a quick upgrade, I can confirm it works. :slightly_smiling_face:

I just wonder where this route comes from:

```
C    *> 0.0.0.0/24 is directly connected, wg0
```

```
 wireguard wg0 {
     address 172.23.1.3/24
     address 2001:xxx:xxx:xxxx::3/64
     listen-port 51820
     peer xyz= {
         allowed-ips ::0/0,0.0.0.0/0
         endpoint x.x.x.x:51820
         persistent-keepalive 25
     }
     private-key /config/auth/wg0.key
     route-allowed-ips false
 }
```

**Comment by zx2c4** [comment]
That route probably comes from the policy-based routing you have elsewhere.

**Comment by markuslindenberg** [comment]
Nope, no such thing in this ER-X's configuration & did a fresh reboot.

I can try to reproduce it on a lab ER-Lite later.

**Comment by sskaje** [comment]
edit config.boot, change peer pubkey, same error

```
[edit interfaces wireguard wg0]
+peer KEYNEW {
+    allowed-ips 0.0.0.0/0
+    endpoint my.sskaje.me:54321
+}
-peer KEYOLD {
-    allowed-ips 0.0.0.0/0
-    endpoint my.sskaje.me:54321
-}
[edit]
root@ubnt# commit
[ interfaces wireguard wg0 ]
RTNETLINK answers: File exists

Commit failed
[edit]
root@ubnt# exit
Cannot exit: configuration modified.
Use 'exit discard' to discard the changes and exit.
[edit]
```

latest release.

**Comment by markuslindenberg** [comment]
@sskaje (a) you can't have `0.0.0.0/0` on two peers of the same wireguard interface, how should wg know to which peer it should send the packets? (b) without setting `route-allowed-ips false` wireguard would try to set the route to `0.0.0.0/0` twice on the same interface (`wg0`).

**Comment by markuslindenberg** [comment]
(deleted a comment that didn't make any sense)

**Comment by sskaje** [comment]
@markuslindenberg 
Sorry, forgot to turn it off on my home router. 
Tests passed on my home router(ERL) now.
