### ISSUE TITLE
Needed to add "--force-overwrite" to dpkg command with v0.0.20180731

### ISSUE THREAD

**Issue by farmwald** [Lochnair/vyatta-wireguard#64]
dpkg -i *.deb failed, complaining that it couldn't overwrite an mss-clamp config file due to conflict with a firewall package.
Adding "--force-overwrite" bypassed the problem.

**Comment by Lochnair** [comment]
Shucks, that's a bit unfortunate.

Send me the output of `ls -l /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/` ?

**Comment by farmwald** [comment]
total 8

-rw-r--r--    1 root     root           409 Aug  2 07:20 node.def

-rw-r--r--    1 root     root           360 Mar  5 09:14 node.def.bak



I added the .bak and deleted node.def as my first fix, but that didn’t work.

Mike



*From:* Nils Andreas Svee [mailto:notifications@github.com]
*Sent:* Thursday, August 02, 2018 10:39 AM
*To:* Lochnair/vyatta-wireguard
*Cc:* farmwald; Author
*Subject:* Re: [Lochnair/vyatta-wireguard] Needed to add
"--force-overwrite" to dpkg command with v0.0.20180731 (#64)



Shucks, that's a bit unfortunate.

Send me the output of ls -l
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/
?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lochnair/vyatta-wireguard/issues/64#issuecomment-410008871>,
or mute the thread

**Comment by Lochnair** [comment]
Huh, I guess the divert didn't work somehow then.

Could you run the divert manually and see if it outputs anything?
```
dpkg-divert --package wireguard --rename --divert /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.vyatta --add /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def
```

**Comment by Lochnair** [comment]
Try to remove the diversion first then:
`dpkg-divert --package wireguard --rename --remove /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def`

**Comment by farmwald** [comment]
Removing 'diversion of
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def
to
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.vyatta
by wireguard'



Then retried:

Adding 'diversion of
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def
to
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.vyatta
by wireguard'

Ignoring request to rename file
'/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def'
owned by diverting package 'wireguard'





*From:* Nils Andreas Svee [mailto:notifications@github.com]
*Sent:* Thursday, August 02, 2018 11:34 AM
*To:* Lochnair/vyatta-wireguard
*Cc:* farmwald; Author
*Subject:* Re: [Lochnair/vyatta-wireguard] Needed to add
"--force-overwrite" to dpkg command with v0.0.20180731 (#64)



Try to remove the diversion first then:
dpkg-divert --package wireguard --rename --remove
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lochnair/vyatta-wireguard/issues/64#issuecomment-410025452>,
or mute the thread

**Comment by Lochnair** [comment]
Weirder and weirder.
Alright, can you try to remove wireguard, and then reinstall it again?

**Comment by farmwald** [comment]
Do I have to do anything special to save my wireguard configuration?

By the way, I’m having identical problems on two EdgeRouters – one is a
Edgerouter infinity and the other is an ER-4.

Mike



*From:* Nils Andreas Svee [mailto:notifications@github.com]
*Sent:* Thursday, August 02, 2018 11:54 AM
*To:* Lochnair/vyatta-wireguard
*Cc:* farmwald; Author
*Subject:* Re: [Lochnair/vyatta-wireguard] Needed to add
"--force-overwrite" to dpkg command with v0.0.20180731 (#64)



Weirder and weirder.
Alright, can you try to remove wireguard, and then reinstall it again?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lochnair/vyatta-wireguard/issues/64#issuecomment-410031368>,
or mute the thread

**Comment by Lochnair** [comment]
Nope. The important thing is to **not** do a config save while WireGuard is not installed.

**Comment by farmwald** [comment]
sudo apt-get remove wireguard

Reading package lists... Done

Building dependency tree

Reading state information... Done

The following packages will be REMOVED:

  wireguard

0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.

After this operation, 0 B of additional disk space will be used.

Do you want to continue [Y/n]? y

(Reading database ... 43450 files and directories currently installed.)

Removing wireguard ...

Removing 'diversion of /opt/vyatta/share/perl5/Vyatta/Interface.pm to
/opt/vyatta/share/perl5/Vyatta/Interface.pm.vyatta by wireguard'

Removing 'diversion of
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def
to
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.vyatta
by wireguard'



Reinstall:



sudo dpkg -i *.deb

Selecting previously unselected package wireguard.

(Reading database ... 43199 files and directories currently installed.)

Unpacking wireguard (from wireguard-e1000-0.0.20180731-1.deb) ...

Adding 'diversion of /opt/vyatta/share/perl5/Vyatta/Interface.pm to
/opt/vyatta/share/perl5/Vyatta/Interface.pm.vyatta by wireguard'

Adding 'diversion of
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def
to
/opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.vyatta
by wireguard'

Setting up wireguard (0.0.20180731-1) ...



So, that seems to fix it.

Should I do the same on my other EdgeRouter or wait?

Mike



*From:* Nils Andreas Svee [mailto:notifications@github.com]
*Sent:* Thursday, August 02, 2018 11:54 AM
*To:* Lochnair/vyatta-wireguard
*Cc:* farmwald; Author
*Subject:* Re: [Lochnair/vyatta-wireguard] Needed to add
"--force-overwrite" to dpkg command with v0.0.20180731 (#64)



Weirder and weirder.
Alright, can you try to remove wireguard, and then reinstall it again?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lochnair/vyatta-wireguard/issues/64#issuecomment-410031368>,
or mute the thread

**Comment by Lochnair** [comment]
Yeah I broke the upgrades again. You can just do a clean install and it'll work like it should, though I'd appreciate if I could bother you to test a (hopefully) fixed version in a few.

**Comment by Lochnair** [comment]
Anyone else that tried to upgrade to the broken version, please do a clean install, for the sake of all our sanity's,

**Comment by farmwald** [comment]
I tried the -2 version on my other EdgeRouter and it worked fine.

Thanks for the quick work.

Mike



*From:* Nils Andreas Svee [mailto:notifications@github.com]
*Sent:* Thursday, August 02, 2018 12:19 PM
*To:* Lochnair/vyatta-wireguard
*Cc:* farmwald; Author
*Subject:* Re: [Lochnair/vyatta-wireguard] Needed to add
"--force-overwrite" to dpkg command with v0.0.20180731 (#64)



Yeah I broke the upgrades again. You can just do a clean install and it'll
work like it should, though I'd appreciate if I could bother you to test a
(hopefully) fixed version in a few.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lochnair/vyatta-wireguard/issues/64#issuecomment-410038101>,
or mute the thread
