### ISSUE TITLE
A route to 0.0.0.0/24 is added automatically on a wg interface

### ISSUE THREAD

**Issue by markuslindenberg** [Lochnair/vyatta-wireguard#7]
This only happens on Edgerouters (I tested with 0.0.20170612 on ER-Lite-3 and ER-X), can't reproduce on a Debian box w/ 0.0.20170613-1.  

```bash
ubnt@ubnt:~$ sudo -i
root@ubnt:~# wg
root@ubnt:~# ip -4 r
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.1 
root@ubnt:~# ip link add dev wg0 type wireguard
root@ubnt:~# ip addr add 10.0.0.1/24 dev wg0
root@ubnt:~# ip link set up dev wg0
root@ubnt:~# ip -4 r
0.0.0.0/24 dev wg0  proto kernel  scope link 
10.0.0.0/24 dev wg0  proto kernel  scope link  src 10.0.0.1 
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.1 
```

**Comment by Lochnair** [comment]
That's peculiar. What kernel version are you running on the Debian box? My gut says compat code, but this is @zx2c4's area.

**Comment by markuslindenberg** [comment]
The Debian box is running the latest kernel from Debian stretch:

```
Linux vhost1 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux
```

**Comment by brianredbeard** [comment]
I saw the same behavior happening on EdgeOS version `1.9.7+hotfix.3`.  I've seen this on the ER-X and the EdgeRouter Pro 8-Port:

```
uname -a
Linux ur1 3.10.20-UBNT #1 SMP Wed Aug 30 03:13:17 PDT 2017 mips64 GNU/Linux 
```

Interestingly enough while i see that route in the output of `show ip route` I do _not_ see it as a path when doing an actual lookup (e.g. `show ip route 8.8.8.8`).  After digging in a bit further, I find that this happens with _other_ VPN mechanisms as well:

```
ubnt@panic:~$ show interfaces openvpn 
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address                        S/L  Description                 
---------    ----------                        ---  -----------                 
vtun0        10.252.252.1/27                   u/u   
```

```
ubnt@panic:~$ show ip route 0.0.0.0/27
Routing entry for 0.0.0.0/27
  Known via "connected", distance 0, metric 0,  External Route Tag: 0, best
  * is directly connected, vtun0
ubnt@panic:~$ show ip route 0.0.0.0/25
Routing entry for 0.0.0.0/25
  Known via "connected", distance 0, metric 0,  External Route Tag: 0, best
  * is directly connected, wg0
ubnt@panic:~$ show ip route 8.8.8.8
Routing entry for 0.0.0.0/0
  Known via "static", distance 210, metric 0,  External Route Tag: 0, best
  * 98.XXX.XXX.1, via eth0
```

This leads me to squarely believe this is an implementation issue within EdgeOS/Vyatta.

**Comment by Lochnair** [comment]
@brianredbeard Thanks for looking into this Brian. I'll close this issue then, since it's not related to Wireguard.

**Comment by brianredbeard** [comment]
Also, FYI for anyone who stumbles across Ubnt will maybe possibly someday _actually_ fix it:

[UBNT Forums - Routing Table Entry 0.0.0.0/24](https://web.archive.org/web/20171006021030/https://community.ubnt.com/t5/EdgeMAX/Routing-Table-Entry-0-0-0-0-24/td-p/1689797)

**Comment by markuslindenberg** [comment]
Thanks so much for the analysis.

**Comment by sslupsky** [comment]
Thanks for this info @brianredbeard .  I was wondering why that route was showing up on my Edgerouters.
