### ISSUE TITLE
New wireguard package fails to install.

### ISSUE THREAD

**Issue by dsully** [Lochnair/vyatta-wireguard#73]
```
# dpkg -i wireguard-ugwxg-0.0.20180904-1.deb
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
(Reading database ... 37820 files and directories currently installed.)
Preparing to replace wireguard 0.0.20180809-1 (using wireguard-ugwxg-0.0.20180904-1.deb) ...
Unpacking replacement wireguard ...
dpkg: error processing wireguard-ugwxg-0.0.20180904-1.deb (--install):
 corrupted filesystem tarfile - corrupted package archive
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 wireguard-ugwxg-0.0.20180904-1.deb
```

**Comment by whiskerz007** [comment]
`Version:      v1.10.6
Build ID:     5112668
Build on:     08/09/18 07:44
Copyright:    2012-2018 Ubiquiti Networks, Inc.
HW model:     EdgeRouter 6P
HW S/N:       ************
Uptime:       12:22:11 up 8 days, 11:57,  2 users,  load average: 0.23, 0.19, 0.23`

`tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
(Reading database ... 35190 files and directories currently installed.)
Preparing to replace wireguard 0.0.20180809-1 (using wireguard-e300-0.0.20180904-1.deb) ...
Unpacking replacement wireguard ...
dpkg: error processing wireguard-e300-0.0.20180904-1.deb (--install):
 corrupted filesystem tarfile - corrupted package archive
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 wireguard-e300-0.0.20180904-1.deb`

**Comment by ev0rtex** [comment]
I get something similar on my EdgeRouter 4. I first tried to install on firmware 1.10.5 and then I just upgraded the firmware from v1.10.5 to v1.10.6 and then did this:
```sh
<user>@<host>:~$ curl -LO https://github.com/Lochnair/vyatta-wireguard/releases/download/0.0.20180904-1/wireguard-e300-0.0.20180904-1.deb
...
<user>@<host>:~$ sudo dpkg -i wireguard-e300-0.0.20180904-1.deb
```
...and got roughly the same output as others above:
```
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
tar: warning: skipping header 'x'
Selecting previously unselected package wireguard.
(Reading database ... 34938 files and directories currently installed.)
Unpacking wireguard (from wireguard-e300-0.0.20180904-1.deb) ...
Adding 'diversion of /opt/vyatta/share/perl5/Vyatta/Interface.pm to /opt/vyatta/share/perl5/Vyatta/Interface.pm.vyatta by wireguard'
Adding 'diversion of /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def to /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.vyatta by wireguard'
dpkg: error processing wireguard-e300-0.0.20180904-1.deb (--install):
 corrupted filesystem tarfile - corrupted package archive
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Removing 'diversion of /opt/vyatta/share/perl5/Vyatta/Interface.pm to /opt/vyatta/share/perl5/Vyatta/Interface.pm.vyatta by wireguard'
Removing 'diversion of /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def to /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.vyatta by wireguard'
Errors were encountered while processing:
 wireguard-e300-0.0.20180904-1.deb
```

**Comment by Lochnair** [comment]
No idea why, but busybox tar doesn't like the files created by GNU tar 1.30 for some reason (or so it seems). If I use bsdtar instead it works. I don't even know anymore...

Anyway I've replaced the packages with new ones that I've verified installs.
