### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by kaileu** [Lochnair/vyatta-wireguard#74]
There is a new Firmware Update released for the usg model.
After upgrading and reinstalling wireguard the command ip link add dev wg0 type wireguard is not permitted anymore so its break wireguard for now.

**Comment by Lochnair** [comment]
Did you use the latest release (0.0.20180904)? If so I'd advise redownloading since there was some issues with the archives causing installation to fail.

**Comment by kaileu** [comment]
I tried the last working one. Because this one failed. https://github.com/Lochnair/vyatta-wireguard/issues/73

I will try tomorrow with the latest release and the latest firmware thanks in advance :)

**Comment by Lochnair** [comment]
Ah right, then there's probably something else wrong. What does `modprobe wireguard` output?

**Comment by gabthefencer** [comment]
@Lochnair modprobe on the **usg pro 4** gives this

root@Firewall:/home/idf# ip link add dev wg0 type wireguard
_RTNETLINK answers: Operation not supported_
root@Firewall:/home/idf#modprobe wireguard
_FATAL: Module wireguard not found._



but on the **usg 3**
 everything seems to be running fine

**Comment by Lochnair** [comment]
Ahh, that makes sense. I'll need to update my kernel trees then. Probably won't get around to that before next week, but in the meantime you could try using the E100 release for the USG3. The only reason I maintain separate versions for the UniFi family is that they often lagg behind the ER kernels.

**Comment by 0x2501** [comment]
I complied my own wireguard.ko following Lochnair's instructions (thanks!). If you can't wait, you can download the wireguard.ko here and you are willing to trust a total stranger, you can download the file I compiled [here](https://drive.google.com/open?id=1eiswVVT_LLDBHzrZ_8rJi0HmTCG_MCth) or wait for Lochnair's official release.

**Comment by gabthefencer** [comment]
Hi @Lochnair,  
I tested the new build on the USG-PRO you put on yesterday and it still says that the module is not found... I'm not sure why....  On the other hand, the one for the USG3 is working wonderfully..

**Comment by Lochnair** [comment]
I've finally updated my UGW kernel trees, so make sure you've on the latest firmware before installing the new release (0.0.20180925). Hopefully we can have an issue-free release this time :)

**Comment by gabthefencer** [comment]
It did fixed it, good job man 👍
