### ISSUE TITLE
Keeping up with snapshots

### ISSUE THREAD

**Issue by peterforeman** [Lochnair/vyatta-wireguard#85]
Hi,

First of all: great work! I'm really enjoying the wireguard module for several UBNT routers.

From the wireguard site:

> WireGuard is not yet complete. You should not rely on this code. It has not undergone proper degrees of security auditing and the protocol is still subject to change. We're working toward a stable 1.0 release, but that time has not yet come. There are experimental snapshots tagged with "0.0.YYYYMMDD", but these should not be considered real releases and they may contain security vulnerabilities (which would not be eligible for CVEs, since this is pre-release snapshot software). **If you are packaging WireGuard, you must keep up to date with the snapshots.**

Although the repo seemed to be quite active some time ago, we're already 5 snapshots (almost 3 months) behind.

Is there any progress on automatic builds and keeping up? Do you need help or is there another reason why the repo is falling behind?

Thanks!

**Comment by aswild** [comment]
It looks like @Lochnair has been having trouble with their [Jenkins build](https://build.lochnair.net/job/ubiquiti/job/wireguard/) used to compile the wireguard binaries.

In the mean time, I wrote a script to download/build the binaries for the e300 platform: https://gist.github.com/aswild/41d53a612e15e3561e9ba039a95c3f1d

That gist compiles everything, but it's still a manual process to 1) copy the binaries to the correct place in the vyatta-wireguard repo, 2) update the version in `debian/control` and 3) run `make deb-e300` to rebuild the package.  When I get time I'll update that script to be generic and send a PR to this repo.

If you have an e300 (ER-4 or ER-6P) you can use my build of [wireguard-e300-0.0.20181218-1.deb.gz](https://github.com/Lochnair/vyatta-wireguard/files/2715828/wireguard-e300-0.0.20181218-1.deb.gz) (gunzip it first)

**Comment by phjeltman** [comment]
The Jenkins jobs fails because the patch formerly located at https://dl.lochnair.net/wireguard-remove_prandom_compat.patch is now unavailable.
```
+ curl -s https://dl.lochnair.net/wireguard-remove_prandom_compat.patch
+ patch -p1
patch: **** Only garbage was found in the patch input.
```
Firmware 2.0.0 has now left beta. I adapted the build script posted by @aswild to build for it, but unfortunately ran out of HD space on my Chromebook. Maybe someone with a more powerful machine can have a go?

**Comment by Lochnair** [comment]
@phjeltman I've built kernel modules and the userspace util for 2.0 already: https://build.lochnair.net/job/ubiquiti/job/wireguard-fw2.0/. Not sure if the Vyatta cfg stuff we have will work on 2.0 or not.

Unfortunately I've been rather strapped for time the last few months, so work on personal projects have become even more sporadic than before.

**Comment by aswild** [comment]
Oh sweet, I've been waiting for 2.0 for a while (hooray systemd). I'll try to upgrade this week, but the [forum thread](https://community.ubnt.com/t5/EdgeRouter/EdgeMAX-EdgeRouter-software-version-v2-0-0-has-been-released/td-p/2622433) mentions some potentially significant issues.

I'll happily test Wireguard (and check what changed in the Vyatta config). Has UBNT released GPL/Kernel sources for 2.0.0 final, or are we still using the beta kernel source since presumably it's close enough?

**Comment by phjeltman** [comment]
Kernel version of 2.0.0 final is 4.9.79-UBNT, same as 2.0.0-alpha1 as per https://community.ubnt.com/t5/EdgeMAX-Beta-Blog/New-EdgeRouter-firmware-2-0-0-alpha-1-has-been-released/ba-p/2376224 (login needed to access)

**Comment by whiskerz007** [comment]
@Lochnair I have installed EdgeOS 2.0 on e100 and e300 boxes and installed WireGuard using your 2.0 build and the tunnel I had configured before, between these two boxes, works as expected.

**Comment by aswild** [comment]
Good news, wireguard is up and running on my ER-4 with v2.0.0 using the binaries from https://github.com/Lochnair/vyatta-wireguard/issues/85#issuecomment-452119881 :D

**Comment by peterforeman** [comment]
Great work all! But: this does not really help the average user who watches the releases here 😉  Can we do anything to fix the jenkins build? And: is there a way to reproduce the jenkins build myself?

**Comment by peterforeman** [comment]
I just received a mail about new releases being pushed. Great! Installed and tested for the 1.10 firmware and working - thanks!!  Closing this now.
