### ISSUE TITLE
Put packages for firmware 1.x and 2.x in one tag

### ISSUE THREAD

**Issue by topjor** [Lochnair/vyatta-wireguard#93]
Could you put the releases for firmware 1.x and 2.x in the same tag, with distinguishable filenames so that it is easier to automate the installation on firmware updates. Currently it is the question if the right version is the first tag or the second, and it is hard to easily differentiate between the normal release and v2 release when automating.

I already mentioned this in issue https://github.com/Lochnair/vyatta-wireguard/issues/62#issuecomment-461575174 (for reference)

**Comment by Lochnair** [comment]
Done.
