### ISSUE TITLE
'RTNETLINK answers: Operation not supported' on ERL with 0.0.20190123

### ISSUE THREAD

**Issue by delikat** [Lochnair/vyatta-wireguard#94]
I have an ERLite-3 running EdgeOS v1.10.8. I installed v0.0.20190123 and set up a WireGuard interface:

```
set interfaces wireguard wg0 address 192.168.33.1/24
set interfaces wireguard wg0 listen-port 51820
set interfaces wireguard wg0 route-allowed-ips true
set interfaces wireguard wg0 private-key ...
commit
```

Which resulted in this error:

```
[ interfaces wireguard wg0 ]
RTNETLINK answers: Operation not supported

Commit failed
```

I downgraded to v0.0.20181218 and was able to set up a WG interface without any problems.

**Comment by delikat** [comment]
This seems to have fixed itself after a couple of restarts 🤷‍♂️

**Comment by axelsimon** [comment]
Hitting this error too using `wireguard-e100-0.0.20190123-1` and EdgeOS v2.0.1.
`uname -a` shows:

> Linux router 4.9.79-UBNT #1 SMP Tue Mar 12 16:20:12 UTC 2019 mips64 GNU/Linux

**Comment by axelsimon** [comment]
Alright, I need to learn to read.
I installed a build that only supports the 1.10 FW series on the 2.0 series. Nevermind, sorry for the noise.
